<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>VTTBD_CorePlatform.API</RootNamespace>
	</PropertyGroup>

	<!-- THAM CHIẾU SANG CÁC PROJECT CON (BẮT BUỘC ĐỂ KHÔNG BỊ LỖI NOT FOUND DLL) -->
	<ItemGroup>
		<ProjectReference Include="..\VTTBD-CorePlatform.Application\VTTBD-CorePlatform.Application.csproj" />
		<ProjectReference Include="..\VTTBD-CorePlatform.Infrastructures\VTTBD-CorePlatform.Infrastructures.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>